<?php

namespace app\controllers;

use budyaga\users\models\forms\LoginForm;
use budyaga\users\models\User;
use Yii;

class TerminalController extends \yii\web\Controller
{
    /**
     * @var string
     */
    public $layout = 'terminal';

    public function beforeAction($action)
    {
        if( $this->getRoute() == '/terminal/login' ){}

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /**
     * Show login form or trying to log in
     *
     * @return array|string
     * @throws \yii\base\InvalidConfigException
     */
    public function actionLogin()
    {
        $this->layout = 'terminal-login';
        $arReq = \Yii::$app->getRequest()->getBodyParams();

        if( empty($arReq['CODE']) ){
            return $this->render('login');
        }
        else{
            $userId = (int)$arReq['CODE'];
            $obUser = new LoginForm();
            $obIdentity = User::findIdentity($userId);
            if( empty($obIdentity->email) ){
                echo json_encode(['STATUS' => false]);
                return false;
            }

            $obUser->email = $obIdentity->email;
            $obUser->password = $arReq['CODE'];
            
            $bAuthorized = $obUser->login();
            if( $bAuthorized ){
                echo json_encode(['STATUS' => true]);
            }
            else{
                echo json_encode(['STATUS' => false, 'ERRORS' => $obUser->getErrors()]);
            }
        }
    }

    public function actionCalendar()
    {
        if( Yii::$app->user->can('terminalWork') === false ){
            Yii::$app->user->logout();
            $this->redirect('/terminal/login/');
        }
        
        return $this->render('calendar');
    }

}